name: flutter-build-apk

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: App Flavor.
        required: false
        type: string
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: false
        type: string
      environment:
        description: Environment
        type: environment
      obfuscate:
        description: Obfuscate
        type: boolean
        default: true
      apk-artifact-name:
        description: APK Artifact Name
        required: true
        type: string
      merged-native-libs-symbols-artifact-name:
        description: Merged Native Libs Symbols Artifact Name
        required: true
        type: string
      flutter-build-symbols-artifact-name:
        description: Flutter Build Symbols Artifact Name
        required: true
        type: string
      gen-l10n:
        description: Generate Localization Files
        type: boolean
        default: true
  workflow_call:
    inputs:
      flavor:
        required: false
        type: string
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: false
        type: string
      environment:
        description: Environment
        type: string
      obfuscate:
        description: Obfuscate
        type: boolean
        default: true
      apk-artifact-name:
        description: APK Artifact Name
        required: true
        type: string
      merged-native-libs-symbols-artifact-name:
        description: Merged Native Libs Symbols Artifact Name
        required: true
        type: string
      flutter-build-symbols-artifact-name:
        description: Flutter Build Symbols Artifact Name
        required: true
        type: string
      gen-l10n:
        description: Generate Localization Files
        type: boolean
        default: true
    secrets:
      KEYSTORE_JKS:
        description: Keystore JKS
        required: true
      KEY_PROPERTIES:
        description: Key Properties
        required: true
      GOOGLE_SERVICES_JSON:
        description: Google Services JSON
        required: false
      APP_ENV:
        description: App Environment
        required: false
      SLACK_WEBHOOK_URL:
        description: Slack Webhook URL
        required: true
      DART_DEFINE_FILE:
        description: Dart Define File
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Code Generators
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - if: ${{ inputs.gen-l10n }}
        name: Generate localization files
        run: flutter gen-l10n

      - name: Decode Signing Keys
        run: echo "${{ secrets.KEYSTORE_JKS }}" | base64 --decode > android/app/keystore.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > android/key.properties

      - name: Prepare Dart Define File
        run: echo "${{ secrets.DART_DEFINE_FILE }}" | base64 --decode > dart-define.json

      - name: flutter-version-number
        uses: NiklasLehnfeld/flutter-version-number-action@v1
        id: read-version

      - name: Prepare ENV File
        run: echo "${{ secrets.APP_ENV }}" | base64 --decode > .env

      - if: "${{ inputs.version-code != '' }}"
        name: Bump Version Codes
        run: "sed -i 's/version: ${{ steps.read-version.outputs.version-number }}/version: ${{ inputs.version-code }}/g' pubspec.yaml"

      - name: Prepare Google Services JSON
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > android/app/google-services.json

      - if: "${{ inputs.flavor == '' }}"
        name: Build Normal APK
        run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --release ${{ inputs.obfuscate && format('--obfuscate --split-debug-info=/home/runner/work/{0}/{0}/build/app/outputs/symbols', github.event.repository.name) || '' }} ${{ secrets.DART_DEFINE_FILE && '--dart-define-from-file dart-define.json' }}

      - if: "${{ inputs.flavor != '' }}"
        name: Build Flavored APK
        run: flutter build apk --target-platform android-arm,android-arm64,android-x64 --release --flavor ${{ inputs.flavor }} -t lib/main_${{ inputs.flavor }}.dart ${{ inputs.obfuscate && format('--obfuscate --split-debug-info=/home/runner/work/{0}/{0}/build/app/outputs/symbols', github.event.repository.name) || '' }} ${{ secrets.DART_DEFINE_FILE && '--dart-define-from-file dart-define.json' }}

      - name: Zip Merged Native Libs Symbols
        run: |
          cd build/app/intermediates/merged_native_libs/release/out/lib && zip -r symbols.zip *

      - name: Zip Flutter Build Symbols
        run: |
          cd build/app/outputs/symbols && zip -r symbols.zip *

      - if: "${{ inputs.flavor == '' }}"
        name: Upload Normal APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.apk-artifact-name }}
          path: ./build/app/outputs/bundle/release/app-release.apk

      - if: "${{ inputs.flavor != '' }}"
        name: Upload Flavored APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.apk-artifact-name }}-${{ inputs.flavor }}
          path: ./build/app/outputs/flutter-apk/app-${{ inputs.flavor }}-release.apk

      - name: Upload Merged Native Symbols Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.merged-native-libs-symbols-artifact-name }}
          path: ./build/app/intermediates/merged_native_libs/release/out/lib/symbols.zip

      - name: Upload Flutter Build Symbols Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.flutter-build-symbols-artifact-name }}
          path: ./build/app/outputs/symbols/symbols.zip

      - name: Upload Mapping Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mapping
          path: ./build/app/outputs/mapping/release/mapping.txt

      - name: Upload BOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bom
          path: ./pubspec.lock

      - name: The job has failed
        if: ${{ failure() && inputs.flavor != '' }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_MESSAGE: 'APK Build for `${{ github.event.repository.name }}` :android: with `${{ inputs.flavor }}` flavor failed :x:.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: The job has failed
        if: ${{ failure() && inputs.flavor == '' }}
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_MESSAGE: 'APK Build for `${{ github.event.repository.name }}` :android: failed :x:.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
