name: flutter-build-ipa-self-hosted

on:
  workflow_dispatch:
    inputs:
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: false
        type: string
      flavor:
        description: Flavor. e.g. dev, prod
        required: false
        type: string
      obfuscate:
        description: Obfuscate
        type: boolean
        default: true
      environment:
        description: Environment
        type: string
        default: staging
      app-name:
        description: App Name
        type: string
        default: App Name
        required: true
      ipa-artifact-name:
        description: IPA Artifact Name
        type: string
        default: IPA Artifact Name
        required: true
      runner-archive-artifact-name:
        description: Runner Archive Artifact Name
        type: string
        required: true
      gen-l10n:
        description: Generate Localization Files
        type: boolean
        default: true
  workflow_call:
    inputs:
      version-code:
        description: Version code. e.g. 1.0.3+7
        required: false
        type: string
      flavor:
        description: Flavor. e.g. dev, prod
        required: false
        type: string
      obfuscate:
        description: Obfuscate
        type: boolean
        default: true
      environment:
        description: Environment
        type: string
        default: staging
      app-name:
        description: App Name
        type: string
        default: App Name
        required: true
      ipa-artifact-name:
        description: IPA Artifact Name
        type: string
        default: IPA Artifact Name
        required: true
      runner-archive-artifact-name:
        description: Runner Archive Artifact Name
        type: string
        required: true
      gen-l10n:
        description: Generate Localization Files
        type: boolean
        default: true
    secrets:
      APP_ENV:
        description: App Environment
        required: false
      SLACK_WEBHOOK_URL:
        description: Slack Webhook URL
        required: false

jobs:
  build-ios:
    runs-on: macOS
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: flutter pub get

      - name: Delete Podspec Lock
        run: rm -rf ios/Podfile.lock

      - name: Pods Install
        run: cd ios && pod install --repo-update

      - name: Run Code Generators
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - if: ${{ inputs.gen-l10n }}
        name: Generate localization files
        run: flutter gen-l10n

      - name: Prepare ENV File
        run: echo "${{ secrets.APP_ENV }}" | base64 --decode > .env

      - name: Verify Certificate Installation
        run: security find-identity -p codesigning -v

      - if: "${{ inputs.flavor == '' }}"
        name: Build Normal IPA
        run: flutter build ipa --release --obfuscate --split-debug-info=${{ github.workspace }}/build/app/outputs/symbols

      - if: "${{ inputs.flavor != '' }}"
        name: Build Flavored IPA
        run: flutter build ipa --obfuscate --release --flavor ${{ inputs.flavor }} -t lib/main_${{ inputs.flavor }}.dart --split-debug-info=${{ github.workspace }}/build/app/outputs/symbols

      - name: Upload DSYMs to Firebase
        run: |
          ios/Pods/FirebaseCrashlytics/upload-symbols -gsp ${{ github.workspace }}/ios/Runner${{ format('{0}{1}', inputs.flavor != '' && '/' || '', inputs.flavor ) }}/GoogleService-Info.plist -p ios ${{ github.workspace }}/build/ios/archive/Runner.xcarchive/dSYMs

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.ipa-artifact-name }}${{ format('{0}{1}', inputs.flavor != '' && '-' || '', inputs.flavor) }}
          path: ./build/ios/ipa/${{ inputs.app-name }}.ipa

      - if: ${{ inputs.runner-archive-artifact-name != '' }}
        name: Upload Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.runner-archive-artifact-name}}
          path: ./build/ios/archive/Runner.xcarchive

      - name: Upload BOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: bom
          path: ./pubspec.lock

      - name: The job has failed
        if: ${{ failure() && inputs.flavor == '' }}
        env:
          SLACK_MESSAGE: 'IPA Build for `${{ github.event.repository.name }}` :ios: failed :x:.'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text": "$SLACK_MESSAGE"}'  ${{ secrets.SLACK_WEBHOOK_URL }}
